import type { AppLocale } from "@/i18n/routing";
import { VOCALIZATION_CLASSES } from "@/domain/analysis/vocalization";

/** All 11 user-facing emotional states (MODEL_OUTPUT_CLASSES minus "unknown"). */
export type EmotionalState = Exclude<(typeof VOCALIZATION_CLASSES)[number], "unknown">;

export const EMOTIONAL_STATES: readonly EmotionalState[] = VOCALIZATION_CLASSES.filter(
  (c): c is EmotionalState => c !== "unknown",
);

export const isEmotionalState = (v: string): v is EmotionalState =>
  (EMOTIONAL_STATES as readonly string[]).includes(v);

export type AdCategory = "wellbeing" | "alert" | "natural";

export const STATE_TO_AD_CATEGORY: Record<EmotionalState, AdCategory> = {
  feliz_contento: "wellbeing",
  trinos: "wellbeing",
  descansando: "wellbeing",
  enfadado: "alert",
  pelea: "alert",
  advertencia: "alert",
  dolor: "alert",
  llamada_madre: "natural",
  llamada_apareamiento: "natural",
  atencion: "natural",
};

export interface StatePhraseEntry {
  readonly state: EmotionalState;
  readonly i18n: Record<AppLocale, readonly string[]>;
}

export const STATE_PHRASES: readonly StatePhraseEntry[] = [
  {
    state: "feliz_contento",
    i18n: {
      es: [
        "Tu gato está disfrutando del momento contigo",
        "Se siente cómodo y feliz a tu lado",
        "Ese es el sonido de un gato contento",
        "Tu compañero felino está de buen humor",
        "La felicidad de tu gato es contagiosa",
        "Tu gato expresa bienestar y confianza",
        "Se siente seguro y relajado contigo",
        "Esa vocalización indica satisfacción",
        "Tu gato está en su mejor momento",
        "Un gato que suena así está feliz",
        "Confianza y confort en cada nota",
        "Tu gato te dice que todo está bien",
        "Esas son señales claras de contentamiento",
        "Tu gato disfruta de tu compañía",
        "Un momento de conexión especial",
        "Tu gato se siente como en casa",
        "La voz de un gato a gusto",
        "Bienestar felino en estado puro",
        "Tu gato comparte su alegría contigo",
        "Nada como escuchar a un gato feliz",
      ],
      en: [
        "Your cat is enjoying the moment with you",
        "They feel comfortable and happy by your side",
        "That's the sound of a content cat",
        "Your feline companion is in a good mood",
        "Your cat's happiness is contagious",
        "Your cat is expressing wellbeing and trust",
        "They feel safe and relaxed with you",
        "That vocalization indicates satisfaction",
        "Your cat is at their best",
        "A cat sounding like this is happy",
        "Trust and comfort in every note",
        "Your cat is telling you everything is fine",
        "Those are clear signs of contentment",
        "Your cat is enjoying your company",
        "A special moment of connection",
        "Your cat feels right at home",
        "The voice of a comfortable cat",
        "Pure feline wellbeing",
        "Your cat is sharing their joy with you",
        "Nothing like hearing a happy cat",
      ],
    },
  },
  {
    state: "trinos",
    i18n: {
      es: [
        "Tu gato te está saludando con cariño",
        "Ese trino es una bienvenida entusiasta",
        "Se alegra de verte llegar",
        "Tu gato te reconoce y te saluda",
        "Es un saludo amigable y positivo",
        "Tu gato te da la bienvenida a casa",
        "Ese sonido corto y melódico es un saludo",
        "Se expresa con la emoción de verte",
        "Tu gato quiere interactuar contigo",
        "Un trino significa cariño y reconocimiento",
        "Tu gato te dice 'hola' a su manera",
        "La forma felina de decir 'qué gusto verte'",
        "Tu llegada le llena de emoción",
        "Ese gorjeo es pura bienvenida",
        "Tu gato celebra tu presencia",
        "Un recibimiento cálido y afectuoso",
        "Tu gato expresa alegría al verte",
        "Ese trino es como un abrazo felino",
        "Cuando tu gato trina, te está diciendo 'hola'",
        "Reconocimiento y afecto en cada trino",
      ],
      en: [
        "Your cat is greeting you with affection",
        "That trill is an enthusiastic welcome",
        "They're happy to see you arrive",
        "Your cat recognizes and greets you",
        "It's a friendly, positive greeting",
        "Your cat is welcoming you home",
        "That short, melodic sound is a greeting",
        "They're expressing the emotion of seeing you",
        "Your cat wants to interact with you",
        "A trill means affection and recognition",
        "Your cat is saying 'hello' their way",
        "The feline way of saying 'great to see you'",
        "Your arrival fills them with excitement",
        "That chirp is pure welcome",
        "Your cat celebrates your presence",
        "A warm and affectionate reception",
        "Your cat expresses joy at seeing you",
        "That trill is like a feline hug",
        "When your cat trills, they're saying 'hi'",
        "Recognition and affection in every trill",
      ],
    },
  },
  {
    state: "enfadado",
    i18n: {
      es: [
        "Tu gato muestra señales de irritación",
        "Parece que algo le está molestando",
        "Es mejor darle espacio ahora mismo",
        "Tu gato expresa descontento",
        "Ese sonido indica frustración felina",
        "Tu gato está de mal humor",
        "No es buen momento para acariciarle",
        "La irritación de tu gato es audible",
        "Tu gato necesita calma y distancia",
        "Esas señales indican enfado",
        "Tu gato comunica que algo no le gusta",
        "Mejor respetar su espacio en este momento",
        "Un gato enfadado pide ser escuchado",
        "Tu gato expresa su desacuerdo",
        "Ese tono revela incomodidad",
        "Tu gato está comunicando malestar",
        "Es tiempo de darle tranquilidad",
        "La irritación felina es una señal clara",
        "Tu gato pide que le dejes en paz",
        "Ese sonido no es de contentamiento",
      ],
      en: [
        "Your cat is showing signs of irritation",
        "Something seems to be bothering them",
        "It's best to give them space right now",
        "Your cat is expressing displeasure",
        "That sound indicates feline frustration",
        "Your cat is in a bad mood",
        "Not a good time to pet them",
        "Your cat's irritation is audible",
        "Your cat needs calm and distance",
        "Those signs indicate anger",
        "Your cat is communicating displeasure",
        "Better respect their space right now",
        "An angry cat wants to be heard",
        "Your cat is expressing disagreement",
        "That tone reveals discomfort",
        "Your cat is communicating unease",
        "Time to give them some peace",
        "Feline irritation is a clear signal",
        "Your cat is asking to be left alone",
        "That sound is not one of contentment",
      ],
    },
  },
  {
    state: "pelea",
    i18n: {
      es: [
        "Se detectó un conflicto intenso entre gatos",
        "Tu gato podría estar en una confrontación",
        "Esos sonidos indican una pelea felina",
        "Intervención puede ser necesaria con precaución",
        "Vocalizaciones de defensa o ataque detectadas",
        "Tu gato está en una situación de conflicto",
        "Se recomienda separar a los gatos con cuidado",
        "Ese nivel de intensidad sugiere agresión directa",
        "Los gatos están resolviendo un conflicto",
        "Es importante no intervenir con las manos",
        "Confrontación territorial en curso",
        "Tu gato se está defendiendo o atacando",
        "Esa intensidad indica una disputa seria",
        "Distráelos con un ruido para interrumpir",
        "Esa no es una vocalización amigable",
        "Conflicto felino activo: actúa con cautela",
        "Tu gato está en modo de confrontación",
        "Esos chillidos indican pelea",
        "Separar con una barrera física es lo más seguro",
        "Intensidad de pelea detectada: supervisión recomendada",
      ],
      en: [
        "An intense conflict between cats was detected",
        "Your cat might be in a confrontation",
        "Those sounds indicate a feline fight",
        "Intervention may be needed, with caution",
        "Defensive or aggressive vocalizations detected",
        "Your cat is in a conflict situation",
        "It's recommended to separate the cats carefully",
        "That intensity level suggests direct aggression",
        "The cats are resolving a conflict",
        "It's important not to intervene with bare hands",
        "Territorial confrontation in progress",
        "Your cat is defending or attacking",
        "That intensity indicates a serious dispute",
        "Distract them with a noise to interrupt",
        "That is not a friendly vocalization",
        "Active feline conflict: proceed with caution",
        "Your cat is in confrontation mode",
        "Those yowls indicate a fight",
        "Separating with a physical barrier is safest",
        "Fight-level intensity detected: supervision recommended",
      ],
    },
  },
  {
    state: "llamada_madre",
    i18n: {
      es: [
        "Una madre está llamando a sus crías",
        "Podría ser una gata buscando a sus gatitos",
        "Esa vocalización es típica de llamada maternal",
        "Tu gata busca a sus pequeños",
        "Patrón melódico descendente de llamada materna",
        "Comunicación entre madre y cría",
        "Una gata llama a sus gatitos cercanos",
        "Vocalización materna dirigida a las crías",
        "Tu gata tiene instinto maternal activo",
        "Ese tono descendente es propio de una madre felina",
        "Llamada de cuidado y protección maternal",
        "Tu gata se comunica con sus gatitos",
        "Voz de madre buscando a sus pequeños",
        "Esa cadencia es típica de comunicación materna",
        "Tu gata llama a sus crías con ese patrón",
        "Instinto maternal en acción",
        "La madre felina localiza a sus gatitos",
        "Ese llamado es de madre a cría",
        "Tu gata expresa cuidado maternal",
        "Comunicación afectiva de madre a gatitos",
      ],
      en: [
        "A mother is calling her kittens",
        "It could be a cat looking for her little ones",
        "That vocalization is typical of a maternal call",
        "Your cat is looking for her kittens",
        "Descending melodic pattern of a mother's call",
        "Communication between mother and offspring",
        "A mother cat is calling nearby kittens",
        "Maternal vocalization directed at young",
        "Your cat has active maternal instincts",
        "That descending tone is typical of a feline mother",
        "A call of maternal care and protection",
        "Your cat is communicating with her kittens",
        "A mother's voice searching for her little ones",
        "That cadence is typical of maternal communication",
        "Your cat is calling her young with that pattern",
        "Maternal instinct in action",
        "The feline mother is locating her kittens",
        "That call is from mother to offspring",
        "Your cat is expressing maternal care",
        "Affective communication from mother to kittens",
      ],
    },
  },
  {
    state: "llamada_apareamiento",
    i18n: {
      es: [
        "Vocalización típica del celo felino",
        "Tu gato podría estar buscando pareja",
        "Ese aullido prolongado indica instinto reproductivo",
        "Sonido característico de celo en gatas",
        "Tu gato expresa necesidad reproductiva",
        "Esa intensidad es típica del apareamiento",
        "Llamada de celo detectada",
        "Si tu gata no está esterilizada, consulta al veterinario",
        "Vocalizaciones de celo son intensas y prolongadas",
        "Tu gato marca su presencia para atraer pareja",
        "Ese canto es propio de la época de celo",
        "Los gatos no castrados vocalizan así al buscar pareja",
        "Considera la esterilización para evitar este comportamiento",
        "Esa vocalización prolongada es de apareamiento",
        "Tu gato busca atención reproductiva",
        "El celo felino produce estos sonidos intensos",
        "Es un comportamiento natural en gatos no castrados",
        "Si es frecuente, la esterilización puede ayudar",
        "Tu gato está en modo de búsqueda de pareja",
        "Esa intensidad es señal de celo activo",
      ],
      en: [
        "Typical feline mating vocalization",
        "Your cat might be seeking a mate",
        "That prolonged yowl indicates reproductive instinct",
        "Characteristic sound of a cat in heat",
        "Your cat is expressing reproductive need",
        "That intensity is typical of mating behavior",
        "Mating call detected",
        "If your cat isn't spayed, consult your vet",
        "Mating vocalizations are intense and prolonged",
        "Your cat is marking their presence to attract a mate",
        "That song is typical of the mating season",
        "Unneutered cats vocalize like this when seeking a mate",
        "Consider spaying/neutering to reduce this behavior",
        "That prolonged vocalization is a mating call",
        "Your cat is seeking reproductive attention",
        "Feline heat produces these intense sounds",
        "This is natural behavior in unneutered cats",
        "If frequent, spaying/neutering may help",
        "Your cat is in mate-seeking mode",
        "That intensity signals active mating behavior",
      ],
    },
  },
  {
    state: "dolor",
    i18n: {
      es: [
        "Tu gato podría estar experimentando dolor",
        "Esa vocalización puede indicar sufrimiento",
        "Es importante revisar si tu gato está bien",
        "Consultar con un veterinario es recomendable",
        "Sonidos como estos pueden señalar malestar físico",
        "Tu gato podría necesitar atención médica",
        "No ignores esta señal: podría ser dolor",
        "Los gatos suelen ocultar el dolor, pero este sonido es una alerta",
        "Si este sonido es nuevo, consulta al veterinario",
        "Tu gato puede estar pidiendo ayuda",
        "Ese meullido puede ser una señal de dolor",
        "La vocalización de dolor es aguda y urgente",
        "Tu gato podría haberse lastimado",
        "Dolor en gatos: mejor prevenir que lamentar",
        "Ese sonido no es normal: vigila de cerca",
        "Tu gato expresa una urgencia que necesita atención",
        "Un cambio en la vocalización puede significar dolor",
        "Los gatos con dolor vocalizan de forma distintiva",
        "Si persiste, no esperes: vuelve al veterinario",
        "Tu gato te está diciendo que algo le duele",
      ],
      en: [
        "Your cat may be experiencing pain",
        "That vocalization might indicate distress",
        "It's important to check if your cat is okay",
        "Consulting a veterinarian is recommended",
        "Sounds like these can signal physical discomfort",
        "Your cat might need medical attention",
        "Don't ignore this signal: it could be pain",
        "Cats often hide pain, but this sound is an alert",
        "If this sound is new, see your vet",
        "Your cat may be asking for help",
        "That meow could be a sign of pain",
        "Pain vocalization is sharp and urgent",
        "Your cat might be hurt",
        "Feline pain: better safe than sorry",
        "That sound isn't normal: monitor closely",
        "Your cat is expressing urgency that needs attention",
        "A change in vocalization can mean pain",
        "Cats in pain vocalize distinctively",
        "If it persists, don't wait: go back to the vet",
        "Your cat is telling you something hurts",
      ],
    },
  },
  {
    state: "descansando",
    i18n: {
      es: [
        "Tu gato está relajado y tranquilo",
        "Ese ronroneo suave indica descanso",
        "Se siente seguro y en calma",
        "Tu gato disfruta de un momento de paz",
        "La tranquilidad de tu gato es evidente",
        "Un gato que suena así está cómodo y relajado",
        "Tu gato está en modo descanso",
        "Ese sonido tranquilizador es de un gato a gusto",
        "Momento de relaxación felina",
        "Tu gato se siente en paz",
        "Un estado de calma y bienestar",
        "Tu gato está descansando plácidamente",
        "Ese ronroneo constante indica confort",
        "Tu gato ha encontrado su punto de tranquilidad",
        "No hay prisa: tu gato está en su zona cómoda",
        "Ese sonido es la banda sonora de un gato tranquilo",
        "Tu gato está recargando energía",
        "Paz felina en estado puro",
        "Tu gato descansa sintiéndose protegido",
        "El sonido de un gato que confía en su entorno",
      ],
      en: [
        "Your cat is relaxed and calm",
        "That soft purr indicates rest",
        "They feel safe and at ease",
        "Your cat is enjoying a peaceful moment",
        "Your cat's tranquility is evident",
        "A cat sounding like this is comfortable and relaxed",
        "Your cat is in rest mode",
        "That soothing sound comes from a content cat",
        "A moment of feline relaxation",
        "Your cat is at peace",
        "A state of calm and wellbeing",
        "Your cat is resting peacefully",
        "That steady purr indicates comfort",
        "Your cat has found their comfort zone",
        "No rush: your cat is in their happy place",
        "That sound is the soundtrack of a calm cat",
        "Your cat is recharging their energy",
        "Pure feline peace",
        "Your cat rests feeling protected",
        "The sound of a cat who trusts their environment",
      ],
    },
  },
  {
    state: "advertencia",
    i18n: {
      es: [
        "Tu gato está diciendo que necesita espacio",
        "Ese siseo es una señal clara de advertencia",
        "Tu gato se siente amenazado: respétale",
        "Es mejor retroceder y dejarle tranquilo",
        "El bufido es una petición de distancia",
        "Tu gato pide que te detengas",
        "No ignores esta señal de advertencia",
        "Tu gato necesita sentirse seguro otra vez",
        "Ese sonido defensivo significa 'no te acerques'",
        "Da a tu gato el espacio que pide",
        "Tu gato está estableciendo un límite",
        "El siseo felino es una advertencia respetable",
        "Tu gato se siente acorralado o amenazado",
        "Respeta la señal: no insistas",
        "Un gato que bufa pide comprensión, no conflicto",
        "Tu gato necesita distancia para calmarse",
        "Esa es una advertencia felina inequívoca",
        "No castigues el siseo: es comunicación sana",
        "Tu gato expresa un límite que debemos respetar",
        "El bufido es lenguaje, no agresión",
      ],
      en: [
        "Your cat is saying they need space",
        "That hiss is a clear warning sign",
        "Your cat feels threatened: respect it",
        "It's best to step back and leave them alone",
        "The hiss is a request for distance",
        "Your cat is asking you to stop",
        "Don't ignore this warning signal",
        "Your cat needs to feel safe again",
        "That defensive sound means 'stay away'",
        "Give your cat the space they're asking for",
        "Your cat is setting a boundary",
        "A feline hiss is a respectable warning",
        "Your cat feels cornered or threatened",
        "Respect the signal: don't insist",
        "A hissing cat asks for understanding, not conflict",
        "Your cat needs distance to calm down",
        "That's an unmistakable feline warning",
        "Don't punish hissing: it's healthy communication",
        "Your cat is expressing a boundary we must respect",
        "A hiss is language, not aggression",
      ],
    },
  },
  {
    state: "atencion",
    i18n: {
      es: [
        "Tu gato quiere que le prestes atención",
        "Ese meullido es una petición explícita",
        "Tu gato te está llamando",
        "Necesita algo de ti: comida, juego o cariño",
        "Un meullido ascendente suele ser una solicitud",
        "Tu gato pide tu atención de forma clara",
        "Algo quiere comunicarte",
        "Tu gato tiene algo que pedirte",
        "Esa vocalización dirigida es una petición",
        "Tu gato te busca activamente",
        "Un meullido con tono ascendente significa 'ven aquí'",
        "Tu gato te necesita ahora mismo",
        "Es hora de prestar atención a tu gato",
        "Tu gato no te ignora: tampoco te ignores",
        "Ese sonido es una petición directa a ti",
        "Tu gato quiere interactuar: responde",
        "Meullido de solicitud: tu gato pide algo",
        "Tu gato te busca con intención",
        "Atención felina: tu gato necesita algo",
        "Tu gato te está hablando directamente",
      ],
      en: [
        "Your cat wants your attention",
        "That meow is an explicit request",
        "Your cat is calling you",
        "They need something from you: food, play, or affection",
        "An ascending meow is usually a solicitation",
        "Your cat is asking for your attention clearly",
        "They want to communicate something",
        "Your cat has something to ask you",
        "That directed vocalization is a request",
        "Your cat is actively seeking you out",
        "A rising-tone meow means 'come here'",
        "Your cat needs you right now",
        "Time to pay attention to your cat",
        "Your cat doesn't ignore you — don't ignore them",
        "That sound is a direct request to you",
        "Your cat wants to interact: respond",
        "Solicitation meow: your cat is asking for something",
        "Your cat is seeking you with purpose",
        "Feline attention: your cat needs something",
        "Your cat is speaking directly to you",
      ],
    },
  },
] as const;

export function getRandomPhrase(state: EmotionalState, locale: AppLocale): string {
  const entry = STATE_PHRASES.find((e) => e.state === state);
  if (!entry) return "";
  const phrases = entry.i18n[locale];
  return phrases[Math.floor(Math.random() * phrases.length)] ?? "";
}

export function getPhrasesForState(state: EmotionalState, locale: AppLocale): readonly string[] {
  const entry = STATE_PHRASES.find((e) => e.state === state);
  if (!entry) return [];
  return entry.i18n[locale];
}