import {
  pgTable,
  uuid,
  text,
  integer,
  timestamp,
  jsonb,
  boolean,
  real,
  index,
  primaryKey,
} from "drizzle-orm/pg-core";

/**
 * Remote schema. Mirrors the local IndexedDB model so sync is a field-by-field
 * mapping. Design goals: referential integrity, cascade delete on account
 * removal (GDPR right to erasure), and append-only analytics/model tables.
 *
 * Migrations are generated by drizzle-kit (drizzle/ dir). Never hand-edit a
 * committed migration; add a new one.
 */

export const users = pgTable("users", {
  id: uuid("id").primaryKey().defaultRandom(),
  email: text("email").notNull().unique(),
  // `name`, `image` and `emailVerified` are the columns the Auth.js
  // DrizzleAdapter reads/writes (the adapter contract). `emailVerifiedAt` is
  // kept for the app's own bookkeeping; Auth.js uses `emailVerified`.
  name: text("name"),
  image: text("image"),
  emailVerified: timestamp("email_verified", { withTimezone: true }),
  emailVerifiedAt: timestamp("email_verified_at", { withTimezone: true }),
  // Monetization: null = free tier. Resolved against subscriptions for entitlements.
  plan: text("plan", { enum: ["free", "premium"] })
    .notNull()
    .default("free"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

/**
 * ── Auth.js (NextAuth v5) adapter tables ───────────────────────────────────
 * Shapes required by `@auth/drizzle-adapter`. The auth-session table is named
 * `auth_sessions` so it never collides with the app's `sessions` table above,
 * which stores ANALYSIS sessions (a completely different concept). Wired in
 * src/server/auth/config.ts via explicit table references.
 */
export const accounts = pgTable(
  "accounts",
  {
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    type: text("type").notNull(),
    provider: text("provider").notNull(),
    providerAccountId: text("provider_account_id").notNull(),
    refresh_token: text("refresh_token"),
    access_token: text("access_token"),
    expires_at: integer("expires_at"),
    token_type: text("token_type"),
    scope: text("scope"),
    id_token: text("id_token"),
    session_state: text("session_state"),
  },
  (t) => [primaryKey({ columns: [t.provider, t.providerAccountId] })],
);

export const authSessions = pgTable("auth_sessions", {
  sessionToken: text("session_token").primaryKey(),
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  expires: timestamp("expires", { withTimezone: true }).notNull(),
});

export const verificationTokens = pgTable(
  "verification_tokens",
  {
    identifier: text("identifier").notNull(),
    token: text("token").notNull(),
    expires: timestamp("expires", { withTimezone: true }).notNull(),
  },
  (t) => [primaryKey({ columns: [t.identifier, t.token] })],
);

export const cats = pgTable(
  "cats",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    birthYear: integer("birth_year"),
    breed: text("breed"),
    sex: text("sex", { enum: ["female", "male", "unknown"] })
      .notNull()
      .default("unknown"),
    traits: jsonb("traits").$type<string[]>().notNull().default([]),
    /** ISO 11784/11785 microchip (15 digits). Nullable; entered by the user. */
    microchip: text("microchip"),
    /** Object-storage key for the cat's photo (set on upload). */
    photoObjectKey: text("photo_object_key"),
    /** Exact birth date (ISO yyyy-mm-dd); enables precise age + the card horoscope. */
    birthDate: text("birth_date"),
    /** Free-form blurb shown on the presentation card. */
    bio: text("bio"),
    /** Chosen presentation-card design + horoscope toggle (mirror of local prefs). */
    cardTemplate: text("card_template", { enum: ["classic", "playful", "elegant"] })
      .notNull()
      .default("classic"),
    showHoroscope: boolean("show_horoscope").notNull().default(false),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("cats_user_idx").on(t.userId)],
);

export const sessions = pgTable(
  "sessions",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    catId: uuid("cat_id").references(() => cats.id, { onDelete: "set null" }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    source: text("source", { enum: ["microphone", "file"] }).notNull(),
    recordingDurationS: real("recording_duration_s").notNull(),
    // We persist features, NOT raw audio, by default (data minimization).
    features: jsonb("features").notNull(),
    segmentStartS: real("segment_start_s").notNull(),
    segmentEndS: real("segment_end_s").notNull(),
  },
  (t) => [index("sessions_user_created_idx").on(t.userId, t.createdAt)],
);

export const predictions = pgTable("predictions", {
  id: uuid("id").primaryKey().defaultRandom(),
  sessionId: uuid("session_id")
    .notNull()
    .references(() => sessions.id, { onDelete: "cascade" }),
  primaryClass: text("primary_class").notNull(),
  primaryProbability: real("primary_probability").notNull(),
  certainty: text("certainty", { enum: ["high", "medium", "low"] }).notNull(),
  ambiguous: boolean("ambiguous").notNull(),
  scores: jsonb("scores").notNull(),
  engineId: text("engine_id").notNull(),
  modelVersion: text("model_version").notNull(),
});

export const feedback = pgTable(
  "feedback",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    sessionId: uuid("session_id")
      .notNull()
      .references(() => sessions.id, { onDelete: "cascade" }),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    verdict: text("verdict", {
      enum: ["correct", "partially-correct", "incorrect"],
    }).notNull(),
    predictedClass: text("predicted_class").notNull(),
    correctedClass: text("corrected_class"),
    sharedForTraining: boolean("shared_for_training").notNull().default(false),
    // Set once an audio donation is uploaded (opt-in); object-storage key.
    audioObjectKey: text("audio_object_key"),
  },
  (t) => [index("feedback_training_idx").on(t.sharedForTraining)],
);

export const subscriptions = pgTable("subscriptions", {
  id: uuid("id").primaryKey().defaultRandom(),
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  provider: text("provider").notNull().default("stripe"),
  providerCustomerId: text("provider_customer_id"),
  status: text("status", {
    enum: ["active", "trialing", "past_due", "canceled"],
  }).notNull(),
  currentPeriodEnd: timestamp("current_period_end", { withTimezone: true }),
});

export const analyticsEvents = pgTable(
  "analytics_events",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id").references(() => users.id, { onDelete: "set null" }),
    name: text("name").notNull(),
    props: jsonb("props").notNull().default({}),
    occurredAt: timestamp("occurred_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("events_name_time_idx").on(t.name, t.occurredAt)],
);

/** Registry the frontend negotiates against; decouples model from app release. */
export const modelVersions = pgTable("model_versions", {
  version: text("version").primaryKey(),
  classes: jsonb("classes").$type<string[]>().notNull(),
  macroF1: real("macro_f1"),
  ece: real("ece"),
  publishedAt: timestamp("published_at", { withTimezone: true }).notNull().defaultNow(),
  isActive: boolean("is_active").notNull().default(false),
});

/** Server-driven flags for staged rollout & monetization toggles. */
export const featureFlags = pgTable("feature_flags", {
  key: text("key").primaryKey(),
  enabled: boolean("enabled").notNull().default(false),
  // Optional percentage rollout 0..100.
  rolloutPct: integer("rollout_pct").notNull().default(0),
});

/** Per-cat learned priors for personalization (E5). Append-only updates. */
export const catPriors = pgTable(
  "cat_priors",
  {
    catId: uuid("cat_id")
      .notNull()
      .references(() => cats.id, { onDelete: "cascade" }),
    cls: text("cls").notNull(),
    // Bayesian counts: how often this cat's sounds were corrected to `cls`.
    alpha: real("alpha").notNull().default(1),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [primaryKey({ columns: [t.catId, t.cls] })],
);

/**
 * ── Medical log (Premium) ──────────────────────────────────────────────────
 * SENSITIVE health data. Treated with explicit consent, never used for model
 * training, and deleted with the cat/account (cascade). The Vet-AI RAG flow
 * reads ONLY the snippets needed to answer a query (see Privacy Policy).
 */
export const vaccinations = pgTable(
  "vaccinations",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    catId: uuid("cat_id")
      .notNull()
      .references(() => cats.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    administeredOn: timestamp("administered_on", { withTimezone: true }).notNull(),
    nextDueOn: timestamp("next_due_on", { withTimezone: true }),
    vet: text("vet"),
    notes: text("notes"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("vaccinations_cat_idx").on(t.catId)],
);

export const medicalRecords = pgTable(
  "medical_records",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    catId: uuid("cat_id")
      .notNull()
      .references(() => cats.id, { onDelete: "cascade" }),
    kind: text("kind", { enum: ["visit", "medication", "condition", "note"] }).notNull(),
    title: text("title").notNull(),
    description: text("description"),
    occurredOn: timestamp("occurred_on", { withTimezone: true }).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("medical_records_cat_idx").on(t.catId)],
);
