import {
  pgTable,
  uuid,
  text,
  integer,
  timestamp,
  jsonb,
  boolean,
  real,
  index,
  primaryKey,
} from "drizzle-orm/pg-core";

/**
 * Remote schema. Mirrors the local IndexedDB model so sync is a field-by-field
 * mapping. Design goals: referential integrity, cascade delete on account
 * removal (GDPR right to erasure), and append-only analytics/model tables.
 *
 * Migrations are generated by drizzle-kit (drizzle/ dir). Never hand-edit a
 * committed migration; add a new one.
 */

export const users = pgTable("users", {
  id: uuid("id").primaryKey().defaultRandom(),
  email: text("email").notNull().unique(),
  emailVerifiedAt: timestamp("email_verified_at", { withTimezone: true }),
  // Monetization: null = free tier. Resolved against subscriptions for entitlements.
  plan: text("plan", { enum: ["free", "premium"] })
    .notNull()
    .default("free"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const cats = pgTable(
  "cats",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    birthYear: integer("birth_year"),
    breed: text("breed"),
    sex: text("sex", { enum: ["female", "male", "unknown"] })
      .notNull()
      .default("unknown"),
    traits: jsonb("traits").$type<string[]>().notNull().default([]),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("cats_user_idx").on(t.userId)],
);

export const sessions = pgTable(
  "sessions",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    catId: uuid("cat_id").references(() => cats.id, { onDelete: "set null" }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    source: text("source", { enum: ["microphone", "file"] }).notNull(),
    recordingDurationS: real("recording_duration_s").notNull(),
    // We persist features, NOT raw audio, by default (data minimization).
    features: jsonb("features").notNull(),
    segmentStartS: real("segment_start_s").notNull(),
    segmentEndS: real("segment_end_s").notNull(),
  },
  (t) => [index("sessions_user_created_idx").on(t.userId, t.createdAt)],
);

export const predictions = pgTable("predictions", {
  id: uuid("id").primaryKey().defaultRandom(),
  sessionId: uuid("session_id")
    .notNull()
    .references(() => sessions.id, { onDelete: "cascade" }),
  primaryClass: text("primary_class").notNull(),
  primaryProbability: real("primary_probability").notNull(),
  certainty: text("certainty", { enum: ["high", "medium", "low"] }).notNull(),
  ambiguous: boolean("ambiguous").notNull(),
  scores: jsonb("scores").notNull(),
  engineId: text("engine_id").notNull(),
  modelVersion: text("model_version").notNull(),
});

export const feedback = pgTable(
  "feedback",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    sessionId: uuid("session_id")
      .notNull()
      .references(() => sessions.id, { onDelete: "cascade" }),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    verdict: text("verdict", {
      enum: ["correct", "partially-correct", "incorrect"],
    }).notNull(),
    predictedClass: text("predicted_class").notNull(),
    correctedClass: text("corrected_class"),
    sharedForTraining: boolean("shared_for_training").notNull().default(false),
    // Set once an audio donation is uploaded (opt-in); object-storage key.
    audioObjectKey: text("audio_object_key"),
  },
  (t) => [index("feedback_training_idx").on(t.sharedForTraining)],
);

export const subscriptions = pgTable("subscriptions", {
  id: uuid("id").primaryKey().defaultRandom(),
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  provider: text("provider").notNull().default("stripe"),
  providerCustomerId: text("provider_customer_id"),
  status: text("status", {
    enum: ["active", "trialing", "past_due", "canceled"],
  }).notNull(),
  currentPeriodEnd: timestamp("current_period_end", { withTimezone: true }),
});

export const analyticsEvents = pgTable(
  "analytics_events",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id").references(() => users.id, { onDelete: "set null" }),
    name: text("name").notNull(),
    props: jsonb("props").notNull().default({}),
    occurredAt: timestamp("occurred_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("events_name_time_idx").on(t.name, t.occurredAt)],
);

/** Registry the frontend negotiates against; decouples model from app release. */
export const modelVersions = pgTable("model_versions", {
  version: text("version").primaryKey(),
  classes: jsonb("classes").$type<string[]>().notNull(),
  macroF1: real("macro_f1"),
  ece: real("ece"),
  publishedAt: timestamp("published_at", { withTimezone: true }).notNull().defaultNow(),
  isActive: boolean("is_active").notNull().default(false),
});

/** Server-driven flags for staged rollout & monetization toggles. */
export const featureFlags = pgTable("feature_flags", {
  key: text("key").primaryKey(),
  enabled: boolean("enabled").notNull().default(false),
  // Optional percentage rollout 0..100.
  rolloutPct: integer("rollout_pct").notNull().default(0),
});

/** Per-cat learned priors for personalization (E5). Append-only updates. */
export const catPriors = pgTable(
  "cat_priors",
  {
    catId: uuid("cat_id")
      .notNull()
      .references(() => cats.id, { onDelete: "cascade" }),
    cls: text("cls").notNull(),
    // Bayesian counts: how often this cat's sounds were corrected to `cls`.
    alpha: real("alpha").notNull().default(1),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [primaryKey({ columns: [t.catId, t.cls] })],
);
