import type { MetadataRoute } from "next";

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "MeowDecoder — Feline acoustic intelligence",
    short_name: "MeowDecoder",
    description: "Analyze and interpret your cat's vocalizations.",
    start_url: "/",
    display: "standalone",
    background_color: "#fffdfa",
    theme_color: "#bf3568",
    // Generated by app/icon.tsx (served at /icon). Avoids shipping/maintaining
    // separate static PNGs and keeps a single source of truth for the brand mark.
    icons: [{ src: "/icon", sizes: "512x512", type: "image/png", purpose: "any" }],
  };
}
